<!DOCTYPE html>
<html>
<head>
    <title>..: Sanclerlândia | Prefeitura Municipal :..</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="Public/css/bootstrap.min.css">
    <link rel="stylesheet" href="Public/css/estilo.css">
</head>
<body>

<div class="container-fluid">
    <div class="col-xs-12 col-sm-12 col-md-5 col-lg-5 B">
        <img src="Public/imagens/logo.png" class="img-responsive center-block">
    </div>
    <div class="col-xs-12 col-sm-12 col-md-7 col-lg-7 G">Menu Bootstrap</div>
    <div class="col-xs-12 col-sm-12 col-md-7 col-lg-7 O">
        <div class="col-md-4">contato</div>
        <div class="col-md-4">telefone</div>
        <div class="col-md-4">busca</div>
    </div>

</div>
<!--<div class="container-fluid">-->
<!--    <div class="row">-->
<!--        <div class="col-md-12">-->
<!--            <div class="carousel slide" id="carousel-795494">-->
<!--                <div class="carousel-inner">-->
<!--                    <div class="item active">-->
<!--                        <img alt="Carousel Bootstrap First" src="http://lorempixel.com/output/sports-q-c-1600-500-1.jpg" style="height: 220px; width: 1600px" />-->
<!--                    </div>-->
<!--                    <div class="item">-->
<!--                        <img alt="Carousel Bootstrap Second" src="http://lorempixel.com/output/sports-q-c-1600-500-2.jpg" style="height: 220px; width: 1600px" />-->
<!--                    </div>-->
<!--                    <div class="item">-->
<!--                        <img alt="Carousel Bootstrap Third" src="http://lorempixel.com/output/sports-q-c-1600-500-3.jpg" style="height: 220px; width: 1600px" />-->
<!--                    </div>-->
<!--                </div>-->
<!--                <a class="left carousel-control tamanho" href="#carousel-795494" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>-->
<!--                <a class="right carousel-control tamanho" href="#carousel-795494" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->

<div class="container-fluid">
<!--    <div class="row">-->
<!--        <div class="col-md-5 col-lg-5 B"></div>-->
<!--        <div class="col-md-4 col-lg-3 G"></div>-->
<!--        <div class="col-md-4 col-lg-3 G"></div>-->
<!--        <div class="col-md-12 col-lg-6 O"></div>-->
<!--    </div>-->
    <img src="Public/imagens/topo.png" class="img-responsive" style="border-top: 4px solid white;">
</div>

<?php
    $this->content();
?>
<hr>
<div class="container-fluid">
    <h2>Accordion Example</h2>
    <p><strong>Note:</strong> The <strong>data-parent</strong> attribute makes sure that all collapsible elements under the specified parent will be closed when one of the collapsible item is shown.</p>
    <div class="panel-group" id="accordion">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">Collapsible Group 1</a>
                </h4>
            </div>
            <div id="collapse1" class="panel-collapse collapse in">
                <div class="panel-body">Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                    sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapse2">Collapsible Group 2</a>
                </h4>
            </div>
            <div id="collapse2" class="panel-collapse collapse">
                <div class="panel-body">Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                    sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapse3">Collapsible Group 3</a>
                </h4>
            </div>
            <div id="collapse3" class="panel-collapse collapse">
                <div class="panel-body">Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                    sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="jumbotron">
        <h1>Rodapé</h1>
    </div>
</div>
<script src="Public/js/jquery-3.2.1.js"></script>
<script src="Public/js/bootstrap.min.js"></script>
</body>
</html>
